/* CRIANDO O DW */ 

CREATE DATABASE CLUBE_DW
GO

/* COMANDO PARA CONECTAR AO BANCO */

USE CLUBE_DW 
GO
-----------------------------------------------------------------
/* CRIANDO AS DIMENSÕES */
-----------------------------------------------------------------
---------------------DIMENSÃO ATIVIDADES (TB_DIM_ATIVIDADES)----------------------


CREATE TABLE TB_DIM_ATIVIDADES 
(
	SK_ATIVIDADE				INT IDENTITY(1,1) 			NOT NULL
	, NK_ATIVIDADE				INT							NOT NULL 
	, NM_ATIVIDADE				VARCHAR(25) 				NOT NULL
	, QT_IDADE_MINIMA			INT							NOT NULL
)
GO
--------------TABELA TEMPORÁRIA---------------------------------
SELECT  IDATIVIDADE 
	    , ATIVIDADE 
	    , IDADE_MINIMA
INTO	#TMP_DIM_ATIVIDADES
FROM	CLUBE_STAGE.dbo.ST_ATIVIDADES


SELECT * FROM #TMP_DIM_ATIVIDADES
GO
---------------INSERT-------------------------------------------
INSERT INTO CLUBE_DW.dbo.TB_DIM_ATIVIDADES 
(
	NK_ATIVIDADE
	, NM_ATIVIDADE
	, QT_IDADE_MINIMA
)
SELECT	IDATIVIDADE 
		, ATIVIDADE
		, IDADE_MINIMA
FROM	 #TMP_DIM_ATIVIDADES							AS m
WHERE  	NOT EXISTS 
		(
			SELECT	1
			FROM	CLUBE_DW.dbo.TB_DIM_ATIVIDADES		AS dm
			WHERE	m.IDATIVIDADE = dm.NK_ATIVIDADE
		)
GO
------------------------UPDATE-----------------------------------------
UPDATE	dm 
SET		NM_ATIVIDADE = m.ATIVIDADE
		, QT_IDADE_MINIMA = m.IDADE_MINIMA
FROM	CLUBE_DW.dbo.TB_DIM_ATIVIDADES					AS dm
		, #TMP_DIM_ATIVIDADES							AS m
WHERE dm.NK_ATIVIDADE = m.IDATIVIDADE 
GO
-----------------------DIMENSÃO FUNCIONÁRIOS (TB_DIM_FUNCIONARIOS)---------------------------------------
CREATE TABLE TB_DIM_FUNCIONARIOS 
(
	SK_FUNCIONARIO				INT IDENTITY(1,1) 			NOT NULL
	, NK_FUNCIONARIO			INT							NOT NULL 
	, NM_NOME					VARCHAR(100) 				NOT NULL
	, NM_SEXO					VARCHAR(20)					NOT NULL
	, DT_NASCIMENTO				DATE						NOT NULL
	, NM_DEPARTAMENTO			VARCHAR(25)					NOT NULL
	, NM_RUA					VARCHAR(150)				NOT NULL
	, NM_BAIRRO					VARCHAR(100)				NOT NULL
	, NM_CIDADE					VARCHAR(100)				NOT NULL
	, NM_ESTADO					VARCHAR(100)				NOT NULL
)
GO
-----------------------TABELA TEMPORÁRIA---------------------------------
SELECT  IDFUNCIONARIO 
	    , NOME 
	    , SEXO
		, NASCIMENTO
		, DEPARTAMENTO
		, RUA
		, BAIRRO
		, CIDADE
		, ESTADO
INTO	#TMP_DIM_FUNCIONARIOS
FROM	CLUBE_STAGE.dbo.ST_FUNCIONARIOS
GO


SELECT * FROM #TMP_DIM_FUNCIONARIOS
GO
-----------------------INSERT-----------------------------------------------
INSERT INTO CLUBE_DW.dbo.TB_DIM_FUNCIONARIOS 
(
	NK_FUNCIONARIO
	, NM_NOME
	, NM_SEXO 
	, DT_NASCIMENTO
	, NM_DEPARTAMENTO
	, NM_RUA
	, NM_BAIRRO
	, NM_CIDADE
	, NM_ESTADO
)


SELECT	IDFUNCIONARIO 
		, NOME
		, SEXO
		, NASCIMENTO
		, DEPARTAMENTO
		, RUA
		, BAIRRO
		, CIDADE
		, ESTADO
FROM	 #TMP_DIM_FUNCIONARIOS								AS m
WHERE  	NOT EXISTS 
		(
			SELECT	1
			FROM	CLUBE_DW.dbo.TB_DIM_FUNCIONARIOS		AS dm
			WHERE	m.IDFUNCIONARIO = dm.NK_FUNCIONARIO
		)
GO
--------------------------UPDATE-----------------------------------------
UPDATE	dm 
SET		NM_NOME = m.NOME
		, NM_SEXO = m.SEXO
		, DT_NASCIMENTO = m.NASCIMENTO
		, NM_DEPARTAMENTO = m.DEPARTAMENTO
		, NM_RUA = m.RUA
		, NM_BAIRRO = m.BAIRRO
		, NM_CIDADE = m.CIDADE
		, NM_ESTADO = m.ESTADO
FROM	CLUBE_DW.dbo.TB_DIM_FUNCIONARIOS		AS dm
		, #TMP_DIM_FUNCIONARIOS					AS m
WHERE dm.NK_FUNCIONARIO = m.IDFUNCIONARIO
GO
-----------------------DIMENSÃO INSCRITOS (TB_DIM_INSCRITOS)------------------------------------------------

CREATE TABLE TB_DIM_INSCRITOS
(
	SK_INSCRITO					INT IDENTITY(1,1) 			NOT NULL
	, NK_INSCRITO				INT							NOT NULL 
	, NM_NOME					VARCHAR(100) 				NOT NULL
	, NM_SEXO					VARCHAR(20)					NOT NULL
	, QT_IDADE					INT							NOT NULL
	, TX_EMAIL					VARCHAR(100)				NOT NULL
	, NM_SOCIO					VARCHAR(20)					NOT NULL 
	, NM_RUA					VARCHAR(150)				NOT NULL
	, NM_BAIRRO					VARCHAR(100)				NOT NULL
	, NM_CIDADE					VARCHAR(100)				NOT NULL
	, NM_ESTADO					VARCHAR(100)				NOT NULL
	, NM_FAIXA_ETARIA			VARCHAR(100)				NOT NULL
	, NM_PROGRAMA_MKT			VARCHAR(100)				NOT NULL
)
GO
-----------------TABELA TEMPORÁRIA--------------------------------------
SELECT  IDINSCRITO 
	    , NOME 
	    , SEXO
		, IDADE
		, EMAIL
		, SOCIO
		, RUA
		, BAIRRO
		, CIDADE
		, ESTADO
		, FAIXA_ETARIA
		, PROGRAMA_MKT
INTO	#TMP_DIM_INSCRITOS
FROM	CLUBE_STAGE.dbo.ST_INSCRITOS
GO

SELECT * FROM #TMP_DIM_INSCRITOS
GO
----------------INSERT-----------------------------------------------
INSERT INTO CLUBE_DW.dbo.TB_DIM_INSCRITOS 
(
	NK_INSCRITO
	, NM_NOME
	, NM_SEXO 
	, QT_IDADE
	, TX_EMAIL
	, NM_SOCIO
	, NM_RUA
	, NM_BAIRRO
	, NM_CIDADE
	, NM_ESTADO
	, NM_FAIXA_ETARIA
	, NM_PROGRAMA_MKT
)
SELECT	IDINSCRITO 
	    , NOME 
	    , SEXO
		, IDADE
		, EMAIL
		, SOCIO
		, RUA
		, BAIRRO
		, CIDADE
		, ESTADO
		, FAIXA_ETARIA
		, PROGRAMA_MKT
FROM	 #TMP_DIM_INSCRITOS								AS m
WHERE  	NOT EXISTS 
		(
			SELECT	1
			FROM	CLUBE_DW.dbo.TB_DIM_INSCRITOS		AS dm
			WHERE	m.IDINSCRITO = dm.NK_INSCRITO
		)
GO
-------------------------UPDATE-----------------------------------------
UPDATE	dm 
SET		NM_NOME = m.NOME
		, NM_SEXO = m.SEXO
		, QT_IDADE = m.IDADE
		, TX_EMAIL = m.EMAIL
		, NM_SOCIO = m.SOCIO
		, NM_RUA = m.RUA
		, NM_BAIRRO = m.BAIRRO
		, NM_CIDADE = m.CIDADE
		, NM_ESTADO = m.ESTADO
		, NM_FAIXA_ETARIA = m.FAIXA_ETARIA
		, NM_PROGRAMA_MKT = m.PROGRAMA_MKT
FROM	CLUBE_DW.dbo.TB_DIM_INSCRITOS		AS dm
		, #TMP_DIM_INSCRITOS				AS m
WHERE dm.NK_INSCRITO = m.IDINSCRITO
GO
------------------------DIMENSÃO TEMPO (TB_DIM_TEMPO)-----------------------------------------------

CREATE TABLE TB_DIM_TEMPO
(
	SK_TEMPO						INT PRIMARY KEY IDENTITY(1,1)			
	, DT_DATA						DATE									
	, NM_DIA						CHAR(2)									
	, NM_DIA_SEMANA					VARCHAR(10)								
	, NM_NUMERO_MES					CHAR(2)									
	, NM_MES						VARCHAR(10)								
	, NM_QUARTO						TINYINT									
	, NM_NOME_QUARTO				VARCHAR(10)								
	, NM_ANO						CHAR(4)									
	, NM_ESTACAO_ANO				VARCHAR(20)								
	, NM_FIM_SEMANA					CHAR(3)									
	, DT_DATA_COMPLETA				VARCHAR(10)								
)
GO
----------------PROGRAMAÇÃO DA TB_DIM_TEMPO-----------------------------
		-------------------------------
		--CARREGANDO A DIMENSÃO TEMPO--
		-------------------------------

		--EXIBINDO A DATA ATUAL

		PRINT CONVERT(VARCHAR,GETDATE(),113) 

		--ALTERANDO O INCREMENTO PARA INÍCIO EM 5000
		--PARA A POSSIBILIDADE DE DATAS ANTERIORES

		DBCC CHECKIDENT (TB_DIM_TEMPO, RESEED, 50000) 

		--INSERÇÃO DE DADOS NA DIMENSÃO

		DECLARE    @DATAINICIO DATETIME 
				 , @DATAFIM DATETIME 
				 , @DATA DATETIME
		 		  
		PRINT GETDATE() 

				SELECT @DATAINICIO = '1/1/1950' 
					, @DATAFIM = '1/1/2050'

				SELECT @DATA = @DATAINICIO 

		WHILE @DATA < @DATAFIM 
		 BEGIN 
	
			INSERT INTO TB_DIM_TEMPO 
			( 
				  DT_DATA, 
				  NM_DIA,
				  NM_DIA_SEMANA, 
				  NM_NUMERO_MES,
				  NM_MES, 
				  NM_QUARTO,
				  NM_NOME_QUARTO, 
				  NM_ANO 
		
			) 
			SELECT @DATA AS DATA, DATEPART(DAY,@DATA) AS NM_DIA, 

				 CASE DATEPART(DW, @DATA) 
            
					WHEN 1 THEN 'Domingo'
					WHEN 2 THEN 'Segunda' 
					WHEN 3 THEN 'Terça' 
					WHEN 4 THEN 'Quarta' 
					WHEN 5 THEN 'Quinta' 
					WHEN 6 THEN 'Sexta' 
					WHEN 7 THEN 'Sábado' 
             
				END AS NM_DIA_SEMANA,

				 DATEPART(MONTH,@DATA) AS NM_MES, 

				 CASE DATENAME(MONTH,@DATA) 
			
					WHEN 'January' THEN 'Janeiro'
					WHEN 'February' THEN 'Fevereiro'
					WHEN 'March' THEN 'Março'
					WHEN 'April' THEN 'Abril'
					WHEN 'May' THEN 'Maio'
					WHEN 'June' THEN 'Junho'
					WHEN 'July' THEN 'Julho'
					WHEN 'August' THEN 'Agosto'
					WHEN 'September' THEN 'Setembro'
					WHEN 'October' THEN 'Outubro'
					WHEN 'November' THEN 'Novembro'
					WHEN 'December' THEN 'Dezembro'
		
				END AS NM_NOME_MES,
		 
				 DATEPART(qq,@DATA) NM_QUARTO, 

				 CASE DATEPART(qq,@DATA) 
					WHEN 1 THEN 'Primeiro' 
					WHEN 2 THEN 'Segundo' 
					WHEN 3 THEN 'Terceiro' 
					WHEN 4 THEN 'Quarto' 
				END AS NM_NOME_QUARTO 
				, DATEPART(YEAR,@DATA) NM_ANO
	
			SELECT @DATA = DATEADD(dd,1,@DATA)
		END

		UPDATE TB_DIM_TEMPO 
		SET NM_DIA = '0' + NM_DIA 
		WHERE LEN(NM_DIA) = 1 

		UPDATE TB_DIM_TEMPO 
		SET NM_NUMERO_MES = '0' + NM_NUMERO_MES 
		WHERE LEN(NM_NUMERO_MES) = 1 

		UPDATE TB_DIM_TEMPO 
		SET DT_DATA_COMPLETA = NM_ANO + NM_NUMERO_MES + NM_DIA 
		GO


		SELECT * FROM TB_DIM_TEMPO
		GO


		----------------------------------------------
		----------FINS DE SEMANA E ESTAÇÕES-----------
		----------------------------------------------

		DECLARE C_TEMPO CURSOR FOR	
			SELECT SK_TEMPO, DT_DATA_COMPLETA, NM_DIA_SEMANA, NM_ANO FROM TB_DIM_TEMPO
		DECLARE			
					@ID INT,
					@DATA varchar(10),
					@DIASEMANA VARCHAR(20),
					@ANO CHAR(4),
					@FIMSEMANA CHAR(3),
					@ESTACAO VARCHAR(15)
					
		OPEN C_TEMPO
			FETCH NEXT FROM C_TEMPO
			INTO @ID, @DATA, @DIASEMANA, @ANO
		WHILE @@FETCH_STATUS = 0
		BEGIN
			
					 IF @DIASEMANA in ('Domingo','Sábado') 
						SET @FIMSEMANA = 'Sim'
					 ELSE 
						SET @FIMSEMANA = 'Não'

					--ATUALIZANDO ESTACOES

					IF @DATA BETWEEN CONVERT(CHAR(4),@ano)+'0923' 
					AND CONVERT(CHAR(4),@ANO)+'1220'
						SET @ESTACAO = 'Primavera'

					ELSE IF @DATA BETWEEN CONVERT(CHAR(4),@ano)+'0321' 
					AND CONVERT(CHAR(4),@ANO)+'0620'
						SET @ESTACAO = 'Outono'

					ELSE IF @DATA BETWEEN CONVERT(CHAR(4),@ano)+'0621' 
					AND CONVERT(CHAR(4),@ANO)+'0922'
						SET @ESTACAO = 'Inverno'

					ELSE -- @data between 21/12 e 20/03
						SET @ESTACAO = 'Verão'

					--ATUALIZANDO FINS DE SEMANA
	
					UPDATE TB_DIM_TEMPO SET NM_FIM_SEMANA = @FIMSEMANA
					WHERE SK_TEMPO = @ID

					--ATUALIZANDO

					UPDATE TB_DIM_TEMPO SET NM_ESTACAO_ANO = @ESTACAO
					WHERE SK_TEMPO = @ID
		
			FETCH NEXT FROM C_TEMPO
			INTO @ID, @DATA, @DIASEMANA, @ANO	
		END
		CLOSE C_TEMPO
		DEALLOCATE C_TEMPO
		GO
-------------------------FATO (TB_FAT_FATO)----------------------------------------------

CREATE TABLE TB_FAT_FATO 
(
	FK_SK_INSCRITO				INT					NOT NULL			
	, FK_SK_ATIVIDADE			INT					NOT NULL			
	, FK_SK_FUNCIONARIO			INT					NOT NULL			
	, FK_SK_TEMPO				INT					NOT NULL			
	, VL_VALOR					NUMERIC(10,2)		NOT NULL		
	, VL_DESCONTO				NUMERIC(10,2)		NOT NULL		
	, VL_DESCONTO_ANIVERSARIO	NUMERIC(10,2)		NOT NULL		
)
GO
	
	
-----------------------------------------------------------------------
/* CONSTRAINTS - PK */ 

ALTER TABLE TB_DIM_ATIVIDADES ADD CONSTRAINT PK_DIM_ATIVIDADES 
PRIMARY KEY (SK_ATIVIDADE)
GO

ALTER TABLE TB_DIM_FUNCIONARIOS ADD CONSTRAINT PK_DIM_FUNCIONARIOS
PRIMARY KEY (SK_FUNCIONARIO)
GO

ALTER TABLE TB_DIM_INSCRITOS ADD CONSTRAINT PK_DIM_INSCRITOS
PRIMARY KEY (SK_INSCRITO)
GO

ALTER TABLE TB_DIM_INSCRITOS ADD CONSTRAINT PK_DIM_TEMPO
PRIMARY KEY (SK_TEMPO)
GO

ALTER TABLE TB_FAT_FATO ADD CONSTRAINT PK_FAT_FATO
PRIMARY KEY (FK_SK_INSCRITO, FK_SK_ATIVIDADE,FK_SK_FUNCIONARIO,FK_SK_TEMPO)
GO
-----------------------------------------------------------------
/* CONSTRAINTS - FK */ 

ALTER TABLE TB_FAT_FATO ADD CONSTRAINT FK_FAT_FATO#FK_SK_INSCRITO 
FOREIGN KEY (FK_SK_INSCRITO) REFERENCES CLUBE_DW.dbo.TB_DIM_INSCRITOS (SK_INSCRITO)
GO

ALTER TABLE TB_FAT_FATO ADD CONSTRAINT FK_FAT_FATO#FK_SK_ATIVIDADE
FOREIGN KEY (FK_SK_ATIVIDADE) REFERENCES CLUBE_DW.dbo.TB_DIM_ATIVIDADES (SK_ATIVIDADE)
GO

ALTER TABLE TB_FAT_FATO ADD CONSTRAINT FK_FAT_FATO#FK_SK_FUNCIONARIO
FOREIGN KEY (FK_SK_FUNCIONARIO) REFERENCES CLUBE_DW.dbo.TB_DIM_FUNCIONARIOS (SK_FUNCIONARIO)
GO

ALTER TABLE TB_FAT_FATO ADD CONSTRAINT FK_FAT_FATO#FK_SK_TEMPO
FOREIGN KEY (FK_SK_TEMPO) REFERENCES CLUBE_DW.dbo.TB_DIM_TEMPO (SK_TEMPO)
GO
---------------------------INSERT------------------------------

INSERT INTO CLUBE_DW.dbo.TB_FAT_FATO
SELECT	di.SK_INSCRITO					
		, da.SK_ATIVIDADE				
		, df.SK_FUNCIONARIO				
		, dt.SK_TEMPO					
		, ft.VALOR
		, ft.DESCONTO
		, ft.DESCONTO_ANIVERSARIO
FROM	CLUBE_STAGE.dbo.ST_FATO							ft
INNER	JOIN CLUBE_DW.dbo.TB_DIM_INSCRITOS 				di 
  ON	ft.ID_INSCRITO = di.NK_INSCRITO
INNER	JOIN CLUBE_DW.dbo.TB_DIM_ATIVIDADES				da
  ON	ft.ID_ATIVIDADE = da.NK_ATIVIDADE
INNER	JOIN CLUBE_DW.dbo.TB_DIM_FUNCIONARIOS			df
  ON	ft.ID_FUNCIONARIO = df.NK_FUNCIONARIO
INNER	JOIN CLUBE_DW.dbo.TB_DIM_TEMPO					dt
  ON	ft.DATA = dt.DT_DATA
GO

select * from clube_stage.dbo.st_fato
go

select * from clube_dw.dbo.tb_dim_tempo
go

